[[environments.default.services]]
name = "backend"
root = "backend"
buildCommand = "pip install -r requirements.txt"
startCommand = "python3 -m uvicorn api_server:app --host 0.0.0.0 --port $PORT --workers 4"

[[environments.default.services]]
name = "frontend"
root = "."
buildCommand = "npm install && npm run build"
startCommand = "npm run start" 